### PR TITLE
Hero Section

### LINKED ISSUE #1: Hero Section
https://www.figma.com/file/Ep77KI4mH4fgrJ1LThyzoQ/Website?type=design&node-id=374-872&mode=design&t=7aL5z30IhYfsxFiF-4

Everything before "Join us for a weekend of memories"

### PR DESCRIPTION
**Pull request by fpunny**
Closes #1 

https://github.com/hack-the-6ix/2024.hackthe6ix.com/assets/23289083/7d23b5d9-5cdd-4a6c-9a78-1651f756a6cf

### CODE REVIEW

**Comment by jeffrey-zang** [comment]
Great work Fred! Few things:

Not quite responsive on wide displays.
image
Designs overflow on the sides
image
Won't nitpick mobile because we don't have mobile designs ready yet.

I think that the colour of the heading text is inconsistent with the design:
image
image
So the contrasting looked a little off but easy fix.

I think we need another issue to clean up the navbar: #9

**Comment by fpunny** [comment]
> Great work Fred! Few things:
> 
> Not quite responsive on wide displays. image Designs overflow on the sides image Won't nitpick mobile because we don't have mobile designs ready yet.
> 
> I think that the colour of the heading text is inconsistent with the design: image image So the contrasting looked a little off but easy fix.
> 
> I think we need another issue to clean up the navbar: #9

 - The assets themselves are clipped, so they are responsive... we just need updated assets from design
 - Fixed the horizontal flow with something quick and dirty (but effective enough and should be an issue if we are responsive)
  - The responsive nav is something that would be tackled later

**Comment by jeffrey-zang** [comment]
Build failed 🤔

**Comment by fpunny** [comment]
@jeffrey-zang ignoring the color thingy because i need to get some more deets from design about it - so we can roll with it for now and "assume" its the right color (We are using the right alias - just the underlying color isnt right)

**Comment by fpunny** [comment]
> Build failed 🤔

doing forward refs for polymorphic components is breaking stuff

**Pull request merged**
